Signup app
macaronu/Twitter_clone pull request #1
Opened 2021-12-28 13:28 UTC by macaronu

ユーザー登録機能をつくりました。

2021-12-29 07:47 UTC, TAK848 requested changes
sessionをうまく使用して誤入力防止をするなど，全体的に良くできていてとても良いと思います！

全体に関するコメントとして以下の2点ご確認お願いします。
頑張っていきましょう！！

## アプリケーション名について
原則，1モデルにつき1アプリという構造にすると見通しが良くなります。
現在，signupというアプリ名になっています。これをuserなどのアプリ名にすることで，user1モデルに対するアクション（signup・signin・signout）をするアプリという見通しの良い構成になるのでお勧めします。

参考:[オニオンアーキテクチャ](https://qiita.com/cocoa-maemae/items/e3f2eabbe0877c2af8d0)
↑難しいですが，原則として1モデル1appという認識を持ってもらえればOKです！

アプリ名を変更するのは意外と大変なのですが，チャレンジしてみてください！
https://qiita.com/donaisore/items/bba92cbd4d95fac575a9

## requirements.txt
[Django girls](https://tutorial.djangogirls.org/ja/django_installation/#requirements%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AB%E3%82%88%E3%81%A3%E3%81%A6%E3%83%91%E3%83%83%E3%82%B1%E3%83%BC%E3%82%B8%E3%82%92%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB%E3%81%99%E3%82%8B)を参考に，`reauirements.txt`を作成して，使用しているライブラリ（Djangoや追加したphonenumbers，phonenumber_field）の一覧とバージョン（Django以外はひとまずなくても可）を明記してください！
例えばですがDjango3.2系を使用しているなら，
```
Django~=3.2
phonenumbers
django-phonenumber-field
```
のように作成してもらえればOKです！Django以外のバージョンを書くかはお任せします。

2021-12-29 07:47 UTC, tak848 commented on mytwitter/urls.py
> +]
最終行に空行を入れましょう。
VSCodeなどのエディタの設定で自動化しておくと楽です！
[設定や由来など参考](https://bottoms-programming.com/archives/indent-tab-space-and-new-line.html#toc5)
他にもテンプレート含めて7ファイルこの状態なので，エディタで設定して保存し直してみてください！

2021-12-29 07:47 UTC, tak848 commented on signup/views.py
> +"""
必要なければ削除しましょう！

2021-12-29 07:47 UTC, tak848 commented on signup/views.py
> +        print (form.errors.as_data())
debug用のprintは削除しましょう！

2021-12-29 07:47 UTC, tak848 commented on mytwitter/views.py
> +from django.shortcuts import render, HttpResponse
`HttpResponse`は使用していないので削除しましょう！

2021-12-29 07:47 UTC, tak848 commented on signup/admin.py
> +class UserAdmin(DjUserAdmin):
Djangoのデフォルトの`UserAdmin`を`as`を用いて無理矢理書き換えるのではなく，`CustomUserAdmin`などの名前で作成することをおすすめします！

2021-12-29 07:47 UTC, tak848 commented on signup/views.py
> +    form = SignupForm(session_form_data1)
`form_data1`や`form_data2`と番号をつけて区別するのは中身が何かわからなってしまいます。
多少長くなっても大丈夫なので，最低限区別のできる別の名前にしましょう！
例としては，`password_form_data`など！

2021-12-29 07:47 UTC, tak848 commented on signup/models.py
> +class User(AbstractUser):
Django標準の`User`と混同しないよう，`CustomUser`とするのをおすすめします！

2021-12-29 07:47 UTC, tak848 commented on signup/views.py
> +from django.views.generic import FormView
使用していないimportを削除しましょう！

2021-12-29 07:47 UTC, tak848 commented on signup/views.py
> +def signupPage(request):
一般に，関数viewは`xx_view`とすることわかりやすいのでお勧めします。他も同様です！
同時に，関数は変数と同様全部小文字+アンダースコアで記述するよう定められているので修正しましょう！

2021-12-29 07:47 UTC, tak848 commented on signup/views.py
> +    return render(request, 'signup/signup.html', {'form':form})
個人的には，
10行目の前に，
```
if request.method == 'GET':
    return render(...
elif request.method == 'POST':
    ...
```
のように書いたほうがわかりやすい気がするのですが，どうでしょう？
そんなことなければスルーしてください！

2021-12-29 07:47 UTC, tak848 commented on mytwitter/views.py
> +def index(request):
一般に，関数viewは`xx_view`とすることわかりやすいのでお勧めします。他も同様です！

2021-12-29 07:47 UTC, tak848 commented on signup/forms.py
> +        BirthYearChoices = range(1901, current_year + 1)
変数として扱うなら全部小文字+区切りはアンダースコア，定数なら全部小文字+区切りはアンダースコアとしましょう！

2021-12-29 07:47 UTC, tak848 commented on signup/templates/signup/password.html
> +<link rel="stylesheet" type="text/css" href="{% static 'signup/style.css' %}">
htmlは最低限，全体はhtmlタグで囲いcssの読み込みはheadタグで囲いましょう。他も同様です！
参考: https://www.kanzaki.com/docs/html/htminfo11.html#S1

2021-12-29 07:47 UTC, TAK848 commented on signup/forms.py
> +import datetime
`ValidationError`は使用していないので削除しましょう！
そしてimportの記述順として，

1. 標準ライブラリ
2. サードパーティに関連するもの
3. ローカルな アプリケーション/ライブラリ に特有のもの

と並べましょう。具体的には，
```suggestion
import datetime

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm

from .models import User
```
こんな感じです。
VSCodeを設定すると，保存するだけで並べ替えられるよう自動化できるのでお勧めです！
https://zenn.dev/wtkn25/articles/python-isort

ついでに余力があればですが，[ここなど](https://itstudio.co/2020/09/26/11077/#toc3)を参照してオートフォーマットを設定するとさらに便利ですのでお勧めです。
Pythonのコーディング規則にもし興味があったら，PEP8で調べてみてください。

2021-12-31 13:18 UTC, macaronu commented on signup/forms.py
> +        BirthYearChoices = range(1901, current_year + 1)
変数としても定数としても、小文字＋アンダースコアということでよろしいでしょうか？？

2021-12-31 13:25 UTC, macaronu commented on mytwitter/views.py
> +def index(request):
class viewはcamelcaseが良いですか？それともsnakecaseが良いですか？

2021-12-31 13:29 UTC, macaronu commented on signup/views.py
> +    return render(request, 'signup/signup.html', {'form':form})
たしかに、そうですね！なんかコードって短ければ短いほうがいいのかなって勝手に思ってたんですけど、一行入れてわかりやすくなるならその方がいいですね。
ちなみに、elseではなくelifを使うのはどうしてでしょうか？GET,POST以外にrequest.methodってあるんですか？

2021-12-31 14:21 UTC, macaronu commented on signup/views.py
> +    return render(request, 'signup/signup.html', {'form':form})
あ、と言いましたがなんかだめでした。validなinputなら耐えるんですが、試しにinvalidなものを入れるとValueErrorが返ってきて、HttpResponseがありませんって言われちゃいます。たぶん、is_validがfalseのときのコードを指定していないからだと思うんですが、元の書き方だとそれが省略できるのでこのまま元のでいこうと思います（笑）

2021-12-31 14:43 UTC, macaronu commented on signup/models.py
> +class User(AbstractUser):
カスタムユーザーモデルだからか、名前を変更してmigrateしようとすると以下と同じような問題が起きてしまいます…
https://stackoverflow.com/questions/58005289/django-renaming-refactoring-a-custom-user-model

そもそもmakemigrationsを走らせるとDid you rename the user.User model to CustomUser?[y/N]と、微妙に見当違いな質問をされます。
y ==> in _get_dependencies_for_foreign_key AttributeError: 'SettingsReference' object has no attribute '_meta' という、よくわかんないエラーが出ます。
N ==> renameされるのではなく、Userモデルを削除して新たにCustomUserを作ろうとしてきます。

また、自分で--emptyなmakemigrationsをしてマニュアリーにRenameModel()を走らせる場合
==> __init__にて、ValueError: The field admin.LogEntry.user was declared with a lazy reference to 'user.customuser', but app 'user' doesn't provide model 'customuser'.

と出てきます。お助け願います…

2022-01-01 06:06 UTC, TAK848 commented on signup/models.py
> +class User(AbstractUser):
こちらで試してみたところ，元々のmigrationsが問題起こしてそうでした。Userモデルは内部でいろんなところにリンクされているのでエラーが出てしまっているようです。
各ファイル（`models.py`，`forms.py`，`admin.py`）の命名を変更した上で，`settings.py`の`AUTH_USER_MODEL`を`CustomUser`に変えたのを確認
↓
ひとまず対処法として，一番最初の段階なのでひとまず`user/migrations`フォルダを削除した上で，
```
python manage.py makemigrations user
```
としてuser appを明示的にmakemigrationsしたのちに通常通りmigrateするとうまく行きました！試してみてください！(migrateでもしエラーが出たらdb.sqlite3を削除など試してみてください）

2022-01-01 06:09 UTC, TAK848 commented on signup/views.py
> +    return render(request, 'signup/signup.html', {'form':form})
`is_valid()`でなかったときの処理的にダメでしたね，すみません！

> コードって短ければ短いほうがいいのかなって勝手に思ってたんですけど、一行入れてわかりやすくなるならその方がいいですね

基本的にそうですね！簡潔にしようとしすぎてもわかりにくくなったり，冗長にしすぎるのは無駄だったりとバランスが意外と難しいので少しずつ慣れていけば良いと思います！

2022-01-01 06:09 UTC, TAK848 commented on mytwitter/views.py
> +def index(request):
ClassViewならCamelCaseです！
https://qiita.com/naomi7325/items/4eb1d2a40277361e898b

2022-01-01 06:09 UTC, TAK848 commented on signup/forms.py
> +        BirthYearChoices = range(1901, current_year + 1)
ごめんなさいミスです，定数なら全部大文字です！

2022-01-01 06:35 UTC, TAK848 requested changes
sqlite3.exeがルートディレクトリに入ってしまっているので`.gitignore`に入れる，削除するなどして対処お願いします！
キャッシュに残ったまま忘れやすいので一応→https://qiita.com/kohei_wd/items/f1d224c9257d1e242b58

あと，requirements.txtの作成もお願いします！

2022-01-01 06:35 UTC, TAK848 commented on user/tests.py
> +
ここの空行が，空白が残っていてうまく認識されていないので確認お願いします！

2022-01-01 06:35 UTC, TAK848 commented on user/forms.py
> +
前回のレビュー漏れですが，空行削除お願いします！

2022-01-01 06:35 UTC, TAK848 commented on user/urls.py
> +    path('thanks', views.signup_thanks_view, name="thanks")
すみません，こちらもチェック漏れでしたが，pathの第一引数の最後にスラッシュを入れるのが通例なのでつけるようにしてください！
※空文字（''）では不要です。
```suggestion
    path('password/', views.password_view, name="create_password"),
    path('confirm/', views.signup_confirm_view, name="confirm"),
    path('thanks/', views.signup_thanks_view, name="thanks")
```

2022-01-01 06:35 UTC, TAK848 commented on user/admin.py
> +from django.utils.translation import gettext, gettext_lazy as _
前回のレビュー漏れです，すみません。
`gettext`は使用していないので削除しましょう！

追加で，ちょっと細かい点です。`gettext_lazy`関数を`_`として今回一部用いていますが，こちらは他言語対応の時に使われる関数のようです。[公式Doc](https://docs.djangoproject.com/ja/3.2/topics/i18n/translation/)
今回サイトの設定も英語にしていてわざわざそこまで設定する必要がなさそうなので，利用しなくても良い気がします！

2022-01-01 14:27 UTC, macaronu commented on user/admin.py
> +from django.utils.translation import gettext, gettext_lazy as _
実はこれ、adminページをいじりたくて、Djangoの元のadmin.pyにおけるfieldsetsのコードをそのまま引っ張ってきて利用していました。そこでgettext_lazyが使われていたがためにとりあえず入れていたのですが、何にどう使うのかいまいち理解していなかったので助かりました、ありがとうございます！

2022-01-01 14:33 UTC, macaronu commented on user/tests.py
> +
空行に空白が残っているってどういうことでしょうか？あと、空行というのは20ライン目であってますか？

2022-01-01 14:33 UTC, macaronu commented on user/forms.py
> +
了解です！ちなみに、空行があるとどういった問題が起こりうるんですか？

2022-01-17 02:12 UTC, TAK848 requested changes
ほぼOKです！
残りの点対応お願いします！

フォーマット面での指摘が多く面倒に感じたかもしれませんが，チーム開発等において大事になるので覚えていきましょう。
[こちらのコメント](https://github.com/macaronu/Twitter_clone/pull/1#discussion_r776185351)で軽く書いたのですが，空行やimportのソートなどはオートフォーマットを使うと楽にできるので，もしよければ[こちら](http://trelab.info/visual-studio-code/python-vscode%E3%81%A7autopep8%E3%82%92%E9%81%A9%E7%94%A8%E3%81%99%E3%82%8B/#toc12)など参考に，[import順自動化](https://zenn.dev/wtkn25/articles/python-isort)と併せてぜひ設定してみてください！

2022-01-17 02:12 UTC, tak848 commented on .gitignore
> +requirements.txt
`requirements.txt`は`.gitignore`に含めずgit上で管理してください！
これがないと，レビュー者など他者が環境を再現するのが大変です！

2022-01-17 02:12 UTC, tak848 commented on user/admin.py
> +        (('Permissions'), {
```suggestion
        ('Personal info', {'fields': ('date_of_birth', 'email', 'phone')}),
        ('Permissions', {
```
関数ではないので冒頭の()は不要です！
13行目も同様です！

2022-01-17 02:12 UTC, tak848 commented on user/tests.py
> -
返信でも記載しましたとおり，改めて改行を入れてください。

2022-01-17 02:13 UTC, TAK848 commented on user/forms.py
> +
質問ありがとうございます。すみません，このコメントは不要でしたね…クラスの下部に空行をあけるのはどちらでも大丈夫です。調べたところ開けている例の方が多いですね…

---
一般に，複数人でコードを書くなどするときに，可読性を高めて保守性を上げるため，コーディング規約というものを定めることが多いです。Pythonでよく使われるのがPEP8と呼ばれるものです。[日本語のマニュアル](https://pep8-ja.readthedocs.io/ja/latest/)

その中で，空行に関する規約も[こちら](https://pep8-ja.readthedocs.io/ja/latest/#section-8)のように定められています。今回のレビューではスルーしましたが，もし余力があれば，

- トップレベルの関数やクラスは、2行ずつ空けて定義するようにしてください。（=一番最後のimportから次のclassや関数の間は，2行空行を空ける）

といった規約もあるので，合わせてみてください（例えばmytwitter/views.pyの2行目の空行をもう一つ増やすなど）。

もう一つ気になった点としては，[こちらのコメント](https://github.com/macaronu/Twitter_clone/pull/1#discussion_r776185351)でimport順をなおすように指摘しましたが，さらに[PEP8](https://pep8-ja.readthedocs.io/ja/latest/#import)では，

1. 標準ライブラリ(datetimeなど)
2. サードパーティに関連するもの(djangoなど)
3. ローカルな アプリケーション/ライブラリ に特有のもの(.userなど)

の**各間に空行を1行空ける**べき，と定められています。その時に書かなくて申し訳なかったのですが，もしよければ他のものも見直してみてください（例えばmytwitter/urls.pyの17行目と18行目の間に空行を入れるなど）。

2022-01-17 02:14 UTC, TAK848 commented on user/tests.py
> +
修正前のファイルのリンクです。
https://github.com/macaronu/Twitter_clone/blob/9e731748a3ee2e2174d5bcbfbcd431feb621c1e2/signup/tests.py
ここを見てもらって，最終行のあたりを選択してもらうと，以下の画像のように，空白が残っています。
<img width="698" alt="Screen Shot 2022-01-17 at 10 05 34" src="https://user-images.githubusercontent.com/41906969/149690201-3d026c99-5f1f-4a90-9dd0-47408fa6d0a1.png">

最終行の空行は，何も入力しないことで認識されます。
ですが空白が4つ入っていたため普通の行として認識されたため，空行が認識されず，レビュー時に画像のように，No new line at end of fileと表示されていました。
<img width="334" alt="Screen Shot 2022-01-17 at 10 16 28" src="https://user-images.githubusercontent.com/41906969/149690208-b3dc6360-cbb3-40dd-aeae-25af3ce27616.png">

2022-01-18 11:38 UTC, TAK848 commented
`requirements.txt`がなぜかバイナリファイル（画像のように，BINと表示されています）になっていて，テキストファイルとして認識できないため，新たにファイルを作り直すなどして認識されるようにしてください！
<img width="848" alt="Screen Shot 2022-01-18 at 20 36 50" src="https://user-images.githubusercontent.com/41906969/149930491-7b520722-2d73-4a61-b7ab-bd039cd1f75e.png">
参考: [テキストとバイナリ](https://quartet-communications.com/info/topics/3182)

2022-01-18 11:50 UTC, macaronu commented
ダメっす。requirements.txtを作り直してコミットし、プッシュを試みてもEverything up-to-dateと言われてしまいました。いったん削除した状態でもプッシュしてみようと試したのですが、それも同じ結果でした

2022-01-18 11:56 UTC, TAK848 commented
ディレクトリに移動した上で，
```
git rm requirements.txt
touch requirements.txt
```
などして完全に作り直してみてください！

2022-01-18 12:02 UTC, macaronu commented
全く関係のないブランチでやっていましたｗ
できました

2022-01-18 12:03 UTC, TAK848 approved these changes
LGTM!!!!

2022-01-19 03:55 UTC, Akinori13 requested changes
数点コメントしました。確認をお願いします。
テストに関しては、Modelの修正とViewの修正が終わってからコメントします

2022-01-19 03:55 UTC, Akinori13 commented on user/forms.py
> +from django.forms import ModelForm
以下のようにして、formsを使わなければ3行目は必要ないです
```suggestion
from django.forms import ModelForm,  SelectDateWidget
```

2022-01-19 03:55 UTC, Akinori13 commented on mytwitter/settings.py
> +AUTH_USER_MODEL = 'user.CustomUser'
ここは105行目に記載通り、`Internationalization`なので、AUTH_USER_MODELはどこでも構いませんが別の場所に記載してください。

2022-01-19 03:55 UTC, Akinori13 commented on mytwitter/templates/mytwitter/index.html
> +<html>
`http://127.0.0.1:8000/`に訪れた際、画面に表示されないと思います。
Djangoの仕様上、各アプリ配下のTemplateフォルダ以下のフォルダを一度集めて、目的のファイルを探索・表示します。換言すればアプリ配下でなければなりません。mytwitterはアプリではないので表示されないと思います。

見る限り必要ないコードなので、これに関するコードは削除してしまっても構いません。お任せします。

なおsettings.pyの60行目あたりの'DIRS'と'APP_DIRS'を以下のように変更してみると、異なる挙動を確認できます。
[参考記事](https://docs.djangoproject.com/en/4.0/topics/templates/#configuration)
```
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ 'mytwitter/templates' ],
        'APP_DIRS': False,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
```

2022-01-19 03:55 UTC, Akinori13 commented on user/models.py
> +    username = models.CharField(max_length=30, unique=True)
Django本来のバリデータとかが効かなくなります。今回はテストもして欲しいのでデフォルトの機能を使いましょう

2022-01-19 03:55 UTC, Akinori13 commented on user/models.py
> +    email = models.EmailField()
ここはデフォルトで設定されているので大丈夫です

2022-01-19 03:55 UTC, Akinori13 commented on user/templates/user/password.html
> +    </form>
アンカー<a>でもいいですね。任せます

2022-01-19 03:55 UTC, Akinori13 commented on user/templates/user/password.html
> +    <form method="post" novalidate>
ここは何かしらの意味がありますか

2022-01-19 03:55 UTC, Akinori13 commented on user/views.py
> +    return render(request, 'user/signup.html', {'form':form})
formを二回定義することはパフォーマンス上避けましょう
```suggestion
   if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            request.session['info_form_data'] = request.POST
            return redirect('user:create_password')
   else:
       session_form_data = request.session.get('info_form_data')
       form = SignupForm(session_form_data)
   return render(request, 'user/signup.html', {'form':form})
```

2022-01-19 03:55 UTC, Akinori13 commented on user/views.py
> +    return render(request, 'user/signup.html', {'form':form})
以下同

2022-01-19 03:55 UTC, Akinori13 commented on user/templates/user/signup.html
> +    <form method="post" novalidate>
ここのnovalidateは必要ですか

2022-01-19 04:56 UTC, macaronu commented on user/models.py
> +    email = models.EmailField()
emailはそうでしたね、ご指摘ありがとうございます。usernameはデフォルトとは違うmax_lengthを設定してるので残しておきます！

2022-01-19 04:57 UTC, macaronu commented on user/templates/user/password.html
> +    <form method="post" novalidate>
ごめんなさい、質問の「ここ」の意味がよくわからないです…？一応、パスワードを設定する画面になっております。

2022-01-19 04:59 UTC, macaronu commented on user/templates/user/password.html
> +    </form>
ボタンのCSSつくるのが面倒だったのでフォームを使ってごり押しました、お許しを…

2022-01-19 05:34 UTC, macaronu commented on user/models.py
> +    email = models.EmailField()
と思ったらすみません、Django本来のバリデータを効かせる必要がありましたね。消しときます！！

2022-01-19 05:41 UTC, macaronu commented on user/templates/user/signup.html
> +    <form method="post" novalidate>
全く必要ないというか、むしろ変ですね。ありがとうございます。
なぜ入れたのでしょうか…何か意図があったと思うのですが…思い出せません…

2022-01-19 05:43 UTC, Akinori13 commented on user/templates/user/password.html
> +    <form method="post" novalidate>
すみません！`novalidate`を設定する必要はありますか？もしなかったら消しちゃってください！

2022-01-19 05:47 UTC, macaronu commented on user/views.py
> +    return render(request, 'user/signup.html', {'form':form})
おおなるほど、こう書けばよかったんですね。

2022-01-19 14:19 UTC, Akinori13 requested changes
テストについて記載しました。
とても難しいと思いますが、頑張ってください！

2022-01-19 14:19 UTC, Akinori13 commented on user/tests.py
> +class CreateUserFormTest(TestCase):
Formのテストしているのはとてもいいと思います

2022-01-19 14:19 UTC, Akinori13 commented on user/tests.py
> +from django.test import TestCase
テストを追加します。テストは正常系と異常系のどちらも確認してください。正常系と異常系をテストクラスで分けるか関数で分けるかについては特にありませんが、今回は同じクラス内で記載してください。

最低限確認して欲しい項目は以下の通りです。
- リクエストを送信する。（GETでテンプレートが表示されるか）
- 有効なemail, username, password1, password2のデータでリクエストを送信する。
- 入力されてないデータでリクエストを送信する。
- usernameがブランクのデータでリクエストを送信する。
- emailがブランクのデータでリクエストを送信する。
- passwordがブランクのデータでリクエストを送信する。
- 既に存在するユーザーを登録するリクエストを送信する。
- emailが有効な形式でないリクエストを送信する。
- passwordが短すぎる（8文字未満）データでリクエストを送信する。
- usernameに類似したpasswordでリクエストを送信する。
- 全て数字のpasswordでリクエストを送信する。
- password1とpassword2が異なるデータでリクエストを送信する。

以下具体例です。
①ホーム画面が表示されることのテスト
```python
class HomeViewTests(TestCase):
    def test_get(self):
          """GET メソッドでアクセスしてステータスコード200を返されることを確認"""
          response = self.client.get(reverse('blog:home'))
          self.assertEqual(response.status_code, 200)
```
②誤ったメールが送信された場合
```python
class InvalidSignUpTests(TestCase):
    def setUp(self):
        self.url = reverse('user:signup')

    def test_post_failed_invalid_email(self):
        """"@のないemail"""
        invalid_email_data = {
            'username': 'example',
            'email': 'sample',
            'password1': 'n6QXemUy',
            'password2': 'n6QXemUy'
        }
        res = self.client.post(self.url, invalid_email_data )
        self.assertEquals(res.status_code, 200)
        self.assertTrue(res.context.get('form').errors)
        self.assertFalse(User.objects.filter(username='example').exists())
```

2022-01-19 14:21 UTC, Akinori13 commented on user/templates/user/password.html
> +    <form method="post" novalidate>
修正してもらったので大丈夫です！

2022-01-22 03:17 UTC, macaronu commented on user/templates/user/signup.html
> +    <form method="post" novalidate>
思い出しました。デフォルトのポップアップで出てくるerror表示ではなく、わたしが設定したエラー表示を使いたかったのでnovalidateが必要でした。例えばusername欄を空欄にしたときのエラー表示は、日本語のポップアップで「このフィールドは必要です」って出てくるのですが、この表示スタイルを英語でかつ他のエラー表示（例えば不正な電話番号を入れたときの青文字のエラーです）とそろえたかったです。

2022-01-22 13:04 UTC, Akinori13 requested changes
テストにコメントしました。確認をお願いします。

2022-01-22 13:04 UTC, Akinori13 commented on user/tests.py
> +class InvalidSignupTests(TestCase):
とても良いと思います。
1. setupでsession周りを共通化できるのでpasswordとconfirmのviewのテストは分離してもいいのではないでしょうか。
2. なるべく共通化しましょう。①特定のフィールドにテストをするので、それ以外のフィールドは同じになります。明示的に指定しない限り、デフォルト値を用いてみましょう。②post先もなるべく共通化しましょう。

2022-01-27 10:47 UTC, Akinori13 requested changes
1点コメントしました

2022-01-27 10:47 UTC, Akinori13 commented on user/tests.py
> +
クラス間は2行空けましょう

2022-01-28 05:46 UTC, Akinori13 approved these changes

2022-01-28 05:46 UTC, merged