Login, Logout, and Profile editing function
macaronu/Twitter_clone pull request #2
Opened 2022-05-20 06:01 UTC by macaronu

めっちゃ遅れてすみません
機能：
ログイン、ログアウト、パスワード再設定、プロフィール編集の機能をつくりました

2022-05-21 02:56 UTC, TAK848 requested changes
しっかり作り込んであって，とても良くできていてgoodです！！！
いくつかコメントしたのでご確認をお願いします！

あと，
- `media/profile`以下はgitignoreに含めてください！
- 次回以降，test更新時は，テスト成功のスクショなどを貼るようにしてください！

追加で1点，前回の範囲で申し訳ないのですが，`InvalidSignupTests`内に`test_invalid_password`のテストが2つあって片方実行されていないので，こちらも確認をお願いします！

2022-05-21 02:56 UTC, tak848 commented on sent_emails/20220116-125329-1279556945136.log
> +-------------------------------------------------------------------------------
logはgitignoreに入れておきましょう！

2022-05-21 02:56 UTC, tak848 commented on mytwitter/settings.py
> +EMAIL_FILE_PATH = str(BASE_DIR.joinpath('sent_emails'))
```suggestion
EMAIL_FILE_PATH = BASE_DIR / 'sent_emails'
```
もっと簡潔にかけます！
MEDIA_ROOTも同様

2022-05-21 02:56 UTC, tak848 commented on requirements.txt
> +pip==21.3.1
pipを追加した理由って何かありますか？

2022-05-21 02:56 UTC, tak848 commented on requirements.txt
> +pip==21.3.1
<img width="774" alt="Screen Shot 2022-05-20 at 19 08 02" src="https://user-images.githubusercontent.com/41906969/169506097-12888cc7-1cec-4a0b-b842-ce52f6eac6f5.png">
pillowを追加してください！

2022-05-21 02:56 UTC, tak848 commented on mytwitter/urls.py
> +from . import views, settings
そのままで全然OKですが，
```python
from django.conf import settings
```
とすると，汎用性は高くなるみたいです！
https://chico-shikaku.com/2021/10/django-conf-import-setting/

2022-05-21 02:56 UTC, tak848 commented on user/models.py
> +    return 'profile/images/user_{0}/{1}'.format(instance.id, filename)
```suggestion
    return f'profile/images/user_{instance.id}/{filename}'
```
最近のpythonだとあまり`.format()`は見ないので，理由がなければ文字列リテラルがおすすめです

2022-05-21 02:56 UTC, tak848 commented on user/models.py
> +            return "https://i.pinimg.com/550x/7a/95/ef/7a95ef5acbc87c558b3b4d7d0ddb3469.jpg"
property使っていて👍

2022-05-21 02:56 UTC, tak848 commented on user/templates/user/password_reset/password_reset_confirm.html
> +                        <ul>{{field.errors}}</ul>
ちょっと細かいですが
```suggestion
                    {% for field in form %}
                        <p>
                            {{ field.label }} {{ field }}
                        </p>
                        <ul>{{ field.errors }}</ul>
```

2022-05-21 02:56 UTC, tak848 commented on user/views.py
>          form = SignupForm(request.POST)
トップレベルのクラスや関数の間は2行空けましょう！（クラス内のメソッド（関数）は1行）
[参照](https://qiita.com/simonritchie/items/bb06a7521ae6560738a7#%E7%A9%BA%E8%A1%8C%E3%81%AE%E6%95%B0)

2022-05-21 02:56 UTC, tak848 commented on user/views.py
> +    return render(request, 'user/signup/signup.html', {'form':form})
辞書のコロンの後は空白入れましょう
以下同様
```suggestion
    return render(request, 'user/signup/signup.html', {'form': form})
```

2022-05-21 02:56 UTC, tak848 commented on user/views.py
> +        context['page_user']= page_user
1. `request_user`についてですが，使用している箇所が見られなかったので削除しましょう
2. メソッドの前に空行を入れましょう
3. イコールの前に空白が抜けています
4. `super()`の引数は，Python3では原則なくてOKです[参考](https://www.lifewithpython.com/2014/01/python-super-function.html)
```suggestion
    permission_denied_message = "Oops! Seems like you haven't signed in yet."

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        page_user = get_object_or_404(CustomUser, id=self.kwargs['pk'])
        context['page_user'] = page_user
```

2022-05-21 02:56 UTC, TAK848 commented on user/views.py
> +        return context
ここで`get_context_data`をoverrideしていますが，DetailViewではこのような処理を書かなくとも，継承元で`object`というキーでにここでいう`page_user`を設定してくれています。
そのため，この関数がなくとも，テンプレート内では`{{ page_user.xx }}`->`{{ object.user }}`とすれば同様の動作が実現できます。
せっかくDetailViewを使用してくれているので，ClassViewの継承関係が載っているサイト https://ccbv.co.uk/projects/Django/4.0/django.views.generic.detail/DetailView/ も是非参照して活用してみてください！

今回特に参考になるのは以下の2箇所↓
<img width="1210" alt="Screen Shot 2022-05-21 at 10 59 10" src="https://user-images.githubusercontent.com/41906969/169630121-d7e9b144-3cb1-4974-959e-11e88728fe4c.png">
<img width="1215" alt="Screen Shot 2022-05-21 at 10 59 40" src="https://user-images.githubusercontent.com/41906969/169630132-557afa88-e527-4517-96ae-1c4ee9a491a8.png">

2022-05-21 02:56 UTC, TAK848 commented on user/views.py
> +        return super(EditProfileView, self).dispatch(request, *args, **kwargs)
superの引数は同様不要です！

2022-05-21 02:56 UTC, TAK848 commented on user/views.py
> +    return render(request, 'user/user_unauthenticated.html')
このviewに参照されている箇所（`user:authenticated`に飛ばしている箇所）が見つからなかったんですが，どこかで使用していますか？（なければ`urls.py`やテンプレート等削除してもよさそう）

2022-05-21 02:56 UTC, TAK848 commented on user/tests.py
> +        response = self.client.post(reverse('user:signin'), {'username':'test', 'password':'12345'})
1. `reverse('user:signin')`を使い回しているので，urlをどこまでsetUpで使い回すかはお任せしますが，`self.signin_url`とした方が変更時等での影響が減ると思います！（修正は任意です！）
2. `views.py`での指摘と同様，辞書内でのコロンの後は空白を空けましょう！

2022-05-21 02:56 UTC, TAK848 commented on user/tests.py
> +        self.assertNotIn(SESSION_KEY, self.client.session)
SigninのテストのClassなので，Signupのテストは別クラスに分けてください！

2022-05-21 02:56 UTC, TAK848 commented on user/tests.py
> +        self.user.refresh_from_db()
refresh_from_dbは初めてみました！このテストの書き方だと必須ですね，勉強になります！

2022-05-21 02:56 UTC, TAK848 commented on user/tests.py
> +        self.client.login(username="test", password="12345")
このクラス内全てでloginしているので，他も含めてsetUpに移してはいかがでしょうか？

2022-05-21 02:56 UTC, TAK848 commented on user/tests.py
> +class EditProfileTests(TestCase):
Imageがあるので，不正なファイル形式（txt, pdfなど）を投げた時のテストもかけると良いでしょう！
こちらは任意ですが，hello.txtなどの画像ではないファイルの拡張子を，jpegなどに無理やり書き換えた，corrupted imageについてもチェックできると尚goodです！

2022-05-21 02:56 UTC, TAK848 commented on user/views.py
> +from django.contrib.auth import authenticate, login
unused importを削除しましょう！（authenticate, login, ListView）

2022-05-22 13:48 UTC, macaronu commented on requirements.txt
> +pip==21.3.1
あ、これは画像のアップロード周りでいろいろ試してた時に追加したのですが、結局使わなくていいようにできたので消し忘れです。消しときます。

2022-05-22 13:51 UTC, macaronu commented on user/views.py
> +        context['page_user']= page_user
了解です！少しトピック離れますが、「使用していない」というのがわかるようなvscodeのおすすめのextensionあったりしますか…？

2022-05-22 13:53 UTC, macaronu commented on user/views.py
> +    return render(request, 'user/user_unauthenticated.html')
あーー使ってないです。前まではここをLOGIN＿URLにしてたのですが、無駄なページを増やさないほうが良いかなと思って変えました。消しておきます。

2022-05-22 13:54 UTC, macaronu commented on user/tests.py
> +        self.client.login(username="test", password="12345")
確かにそうですね！ありがとうございます。

2022-05-23 09:14 UTC, TAK848 commented on user/views.py
> +        context['page_user']= page_user
これに関しては，左上の虫眼鏡のところから全体検索でrequest_userを検索しました！拡張機能は特に使用していません。
<img width="298" alt="Screen Shot 2022-05-23 at 18 05 14" src="https://user-images.githubusercontent.com/41906969/169784477-8ef0ba6a-80e7-4bdb-979f-f68321f05dc3.png">

---
せっかくなのでトピック外ですがおまけ↓
この件に関しては注意深くチェックしないと気づかないですが，基本的なこと（unused importとか，空行とか，使っていない変数とか）については，flake8による構文解析とautopep8によるフォーマットがおすすめです。一目で気づく+直せるところは勝手に直してくれます。割とこれに関する指摘を多くしている気がするので，導入おすすめ！

VSCodeのsettings.jsonに以下の設定を足しています。
多分`"python.linting.flake8Enabled": true,`と設定に書くと，右下にflake8インストールする？みたいのが出てくるのでOKするとわかるようになるはず
さらに保存するとautopep8入れますか？と出て以降は勝手にフォーマットしてくれるはず
追加で手動でisortを入れると，勝手に並び替えもしてくれます！
（pythonの拡張機能とこれらのpipによるインストールのみでできます）
```json
    "python.linting.pylintEnabled": false,
    "python.linting.flake8Enabled": true,
    "python.linting.flake8Args": [
        "--ignore=W293, E501",
    ],
    "[python]": {
        "editor.defaultFormatter": "ms-python.python",
        "editor.formatOnSave": true,
    },
```

出てきた以下みたいなproblemを減らしといてくれるとgood!
<img width="518" alt="Screen Shot 2022-05-23 at 18 08 20" src="https://user-images.githubusercontent.com/41906969/169785764-bcc321fb-1ade-4418-b7b0-88aa1eb70ec7.png">
<img width="641" alt="Screen Shot 2022-05-23 at 18 08 29" src="https://user-images.githubusercontent.com/41906969/169785779-816c0e62-25ba-46cc-b788-1b0fdb474280.png">

2022-05-24 04:37 UTC, macaronu commented on user/views.py
> +        return context
これに関してなんですが、この続きの機能でrequestとpageのuserの処理を使い分けたいところ（例えば自分のTweetにはEditを表示するが他人のには表示しないなど）が結構あり、Overrideして書いています。残しておいてもいいですか？

2022-05-24 12:51 UTC, TAK848 requested changes
コメントしました！

一つ質問なんですが，flake8の表示とかってvscodeに出てますか?requirements.txtにflake8が入っていたので
全部守る必要はないですが，結構参考になるはずです！
↓こういうやつ
<img width="73" alt="Screen Shot 2022-05-24 at 21 55 41" src="https://user-images.githubusercontent.com/41906969/170039850-f4ee41b6-75f1-4daa-9562-76ef8375f525.png">

<img width="111" alt="Screen Shot 2022-05-24 at 21 55 57" src="https://user-images.githubusercontent.com/41906969/170039893-8411dc90-c3c2-420e-bdea-08c27f5f40f2.png">
<img width="504" alt="Screen Shot 2022-05-24 at 21 56 07" src="https://user-images.githubusercontent.com/41906969/170039947-b0a59d9a-9bd0-4e29-b7bd-4f2d3d3a18e6.png">

2022-05-24 12:51 UTC, tak848 commented on .gitignore
> +
1. `media/test/`をテストで共通して使用しているので，`media/`->`media/profile/`などとしましょう！
2. 追記したこと自体はOKです！既に追加されてしまったファイルたちが残ってしまっています。「gitignore 反映されない」で[google検索](https://www.google.com/search?q=gitignore%20%E5%8F%8D%E6%98%A0%E3%81%95%E3%82%8C%E3%81%AA%E3%81%84&tbm=&ie=utf-8&oe=utf-8&num=100&hl=&lr=&pws=1&filter=1)してみた結果などを参考に，一度追加されてしまったものをどうにかして削除しましょう！
<img width="309" alt="Screen Shot 2022-05-24 at 15 52 11" src="https://user-images.githubusercontent.com/41906969/169967148-5ce0f391-6c33-4127-b38b-4d0d9334ee34.png">

2022-05-24 12:51 UTC, tak848 commented on user/tests.py
> +            date_of_birth= '1901-01-01'
```suggestion
            phone='',
            date_of_birth='1901-01-01'
```
細かい点すみません！
SigninTestsとGetViewTests，EditViewTestsも同じズレがあるので修正お願いします！

2022-05-24 12:51 UTC, tak848 commented on user/tests.py
> +        redirect_url = reverse('user:user_profile', kwargs={'pk': self.user.id})
これ以下のtestで`redirect_url`が未使用なので削除しましょう！

2022-05-24 12:51 UTC, tak848 commented on user/tests.py
> +        self.assertIn(SESSION_KEY, self.client.session)
446行目（2つ上のテスト）と被っているのでrenameお願いします！

2022-05-24 12:51 UTC, tak848 commented on requirements.txt
> +djangorestframework==3.12.4
DRFは後で使う予定ですか？

2022-05-24 12:51 UTC, TAK848 commented on user/views.py
>      template_name = "user/password_reset/password_reset_form.html"
コメントも含めて2行あけてください！
```python
    template_name = 'user/signedout.html'


# Views for resetting password
class PasswordResetView(PasswordResetView)
```
みたいな感じです！

2022-05-24 12:51 UTC, TAK848 commented on user/views.py
>      def get_context_data(self, **kwargs):
1行あけてください！

2022-05-24 12:51 UTC, TAK848 commented on user/views.py
> +    def dispatch(self, request, *args, **kwargs):
```suggestion
        return False

    # Users cannot access other people's edit pages
    def dispatch(self, request, *args, **kwargs):
```
1行あけてください！

2022-05-24 12:53 UTC, TAK848 commented on user/views.py
> +        return context
意図があれば基本OKです！

さらによくするなら，現状だとuserのgetにクエリが2回発行されてしまうので，page_userに
```python
        context['page_user']= page_user
```
を直接入れてあげると良いかもです。（404も勝手に返してくれます）

2022-05-25 02:47 UTC, TAK848 commented on user/views.py
> +        return context
追記すみません！
https://docs.djangoproject.com/en/4.0/topics/class-based-views/generic-display/#making-friendly-template-contexts
にあるように，
1. クラス変数として，context_object_name = 'page_user'とすることができるみたいです。
2. テンプレート上でrequest.userと何も使用しなくても使えるので，テンプレートでチェックするなら， page_user == request.user みたいなチェックができるかなーと思います。

どれを使ってもOKです！

2022-05-25 04:19 UTC, macaronu commented on requirements.txt
> +djangorestframework==3.12.4
使わないです。pip freezeで雑に作っちゃったのがいけませんでしたね、ちゃんと書きますｗ

2022-05-25 04:19 UTC, macaronu commented on user/views.py
>      template_name = "user/password_reset/password_reset_form.html"
了解です！

2022-05-25 04:49 UTC, macaronu commented
> 

出てませんでした。なんでかなぁと思ったらなぜかvscodeのpythonがDisableされてました笑笑
ありがとうございます。いろいろ直してみます。

2022-05-25 05:28 UTC, macaronu commented on user/views.py
> +        return context
おお！！！これは便利！！ありがとうございます、変えてきます。

2022-05-26 08:25 UTC, tak848 requested changes
ほぼOKです！
tests更新時にこんな感じに
<img width="564" alt="Screen Shot 2022-05-26 at 17 23 48" src="https://user-images.githubusercontent.com/41906969/170449049-3683ff22-b379-4962-9a58-3c227bb18cb8.png">
スクショ貼るようにしてください！

> 出てませんでした。なんでかなぁと思ったらなぜかvscodeのpythonがDisableされてました笑笑
ありがとうございます。いろいろ直してみます。

よかったです！便利な機能はどんどん使いましょう！
レビューも中身により集中できるので助かります！

2022-05-26 08:25 UTC, TAK848 commented on user/urls.py
> +    path('unauthenticated/', views.user_unauthenticated_view, name="unauthenticated"),
まだ残っているので確認お願いします！

2022-05-26 08:25 UTC, TAK848 commented on user/views.py
> +    template_name = 'user/signin.html'
```suggestion
    return render(request, 'user/signup/thanks.html')


# Views for signing in
class SigninView(LoginView):
    template_name = 'user/signin.html'
```
コメントが入って空行が逆に不自然になってしまっているので，ここは手動で修正お願いします！以下も同様

2022-05-26 10:13 UTC, macaronu commented on user/urls.py
> +    path('unauthenticated/', views.user_unauthenticated_view, name="unauthenticated"),
すみません、何が残っているのでしょうか…？

2022-05-26 10:17 UTC, TAK848 commented on user/urls.py
> +    path('unauthenticated/', views.user_unauthenticated_view, name="unauthenticated"),
https://github.com/macaronu/Twitter_clone/pull/2#discussion_r878630461 これです！
unauthenticated_viewをどこでも使っていないよね！という話です！

2022-05-26 10:30 UTC, macaronu commented on user/urls.py
> +    path('unauthenticated/', views.user_unauthenticated_view, name="unauthenticated"),
ありがとうございます！消しました。テストではここのviewとurlは使っていなかったので、変更しませんでした。

2022-05-26 10:31 UTC, macaronu commented
<img width="520" alt="スクリーンショット 2022-05-26 193050" src="https://user-images.githubusercontent.com/79188146/170470847-e27c7bb5-65d9-43c7-a844-695d7b1195c7.png">
こちらテスト成功画面になります。

2022-05-26 11:11 UTC, TAK848 commented
LGTM!!!!

2022-05-26 11:11 UTC, TAK848 approved these changes
LGTM!!!1

2022-05-28 06:43 UTC, Akinori13 requested changes
数点コメントしました

2022-05-28 06:43 UTC, Akinori13 commented on media/test/test_corr.jpg
> +hello world
これ必要ですか

2022-05-28 06:43 UTC, Akinori13 commented on media/test/test_corr.jpg
> +hello world
猫かわいい

2022-05-28 06:43 UTC, Akinori13 commented on user/models.py
>  class CustomUser(AbstractUser):
CustomUserとOneToOneの関係になるProfileモデルを作成していただきたいです

2022-05-28 06:43 UTC, Akinori13 commented on user/views.py
> +        return False
ここでユーザーがログインしていることを確認する必要はありますか

2022-05-28 06:43 UTC, Akinori13 commented on user/views.py
> +    def user_passes_test(self, request):
UserPassesTestMixinは使えないですか

2022-05-30 04:16 UTC, macaronu commented on media/test/test_corr.jpg
> +hello world
こちらはテキストファイルを無理やりjpgに書き換えたcorrupted imageをテストしたくて入れてます！
猫さんは私のフィルムカメラで撮りました、可愛いに決まってら

2022-06-22 05:21 UTC, Akinori13 commented
LGTM

2022-06-22 05:22 UTC, merged