Tweet function
macaronu/Twitter_clone pull request #3
Opened 2022-09-18 02:59 UTC by macaronu

ツイート機能です 😀 

テスト結果：
<img width="463" alt="スクリーンショット 2022-09-18 115601" src="https://user-images.githubusercontent.com/79188146/190883662-95b2082b-ac29-4827-9a53-77acb3f7ee16.png">

2022-09-18 14:54 UTC, fujinomoto62 commented
LGTMです。要件は満たせていると思います。

2022-09-20 01:51 UTC, TAK848 requested changes
よく作り込まれていて良いと思います！
数点細かい点ですがコメントしたのでご確認お願いします！

2022-09-20 01:51 UTC, tak848 commented on tweets/urls.py
> +    path("tweet/", views.TweetCreateView.as_view(), name="tweet"),
`tweets/tweet/`だとなんだかよくわかりづらいので，`tweets/create/`や`tweets/compose/`などとしましょう

2022-09-20 01:51 UTC, tak848 commented on tweets/forms.py
> +        widgets = {"body": Textarea(attrs={"placeholder": "What's Happening?"})}
good

2022-09-20 01:51 UTC, tak848 commented on user/views.py
> +    permission_denied_message = "Oops! Seems like you haven't signed in yet."
`LoginRequiredMixin`にこんなのあるんですね…
初めて知りました！いいですね！

2022-09-20 01:51 UTC, tak848 commented on tweets/models.py
> +    replies = models.IntegerField(default=0)
規模の大きなサービスになってくると，整合性を保つのが困難になってくるので，Likeの数などをフィールドとして持つのではなく，機能導入時に，集計のcountをして入れていくのが良いと思います。（いいねを追加・削除するたびにこちらのカウントを整合性が取れるように調節するのは不可能ではないですが難しくなっていきます）

2022-09-20 01:51 UTC, tak848 commented on tweets/models.py
> +    updated_at = models.DateTimeField(auto_now=True)
created_atとupdated_atはrepliesの下の行などに移動させた方が，情報の重要性的にさらにわかりやすいと思います

2022-09-20 01:51 UTC, tak848 commented on user/templates/user/home.html
> +                        <a class="prof-name" style="float: left; margin-left: 10px; margin-top: 8px;" href="{% url 'user:user_profile' pk=tweet.user.id %}">{{ tweet.user }}</a>
各ツイートからuser情報を引っ張るN+1になっています。
こちら課題の要件でもあるのでselect_relatedを用いるなどして修正しましょう。

<img width="1130" alt="Screen Shot 2022-09-20 at 9 46 36" src="https://user-images.githubusercontent.com/41906969/191143634-34c3c8e9-fde2-4c85-85fe-8fde31a6c188.png">
[ログを出した方法](https://qiita.com/fumihiko-hidaka/items/0f619749580da5ad9ce5)

2022-09-20 01:51 UTC, tak848 commented on user/templates/user/profile/user_profile.html
> +                        <a class="prof-name" style="float: left; margin-left: 10px; margin-top: 8px;" href="{% url 'user:user_profile' pk=page_user.id %}">{{ tweet.user }}</a>
これもN+1です

2022-09-20 01:51 UTC, TAK848 commented on tweets/urls.py
> +        "<str:username>/<int:pk>/", views.TweetDetailView.as_view(), name="tweet_detail"
username，必要ですか？
tweetのpkは一意なので，なくて良い気がしますが…
（パスの意味的にも，`tweets/<pk>/`とすると，tweetたちの中の，pkと指定する形になり通じます。
一方`tweets/<username>/<pk>/`とすると解釈しずらい。
もしやるなら，`users/<username>/tweets/<pk>/`（ユーザーたちの中でも<username>のユーザーで，そのユーザーのtweetsの中の<pk>番）の方が好ましい）

2022-09-20 02:07 UTC, macaronu commented on tweets/models.py
> +    replies = models.IntegerField(default=0)
なるほど、確かにそうですね！

2022-09-20 02:14 UTC, macaronu commented on tweets/urls.py
> +        "<str:username>/<int:pk>/", views.TweetDetailView.as_view(), name="tweet_detail"
いらないですね。ただ単にツイッターがそういうパスになってたのでクローンならそれにあわせるべきかと思って`tweets/<username>/<pk>/`になってるだけですね。`tweets/<pk>`で十分なので変更しておきます！

2022-09-20 02:24 UTC, macaronu commented on user/templates/user/home.html
> +                        <a class="prof-name" style="float: left; margin-left: 10px; margin-top: 8px;" href="{% url 'user:user_profile' pk=tweet.user.id %}">{{ tweet.user }}</a>
select_related()を使うとかなり負荷減らせますね。ありがとうございます！！

2022-09-20 11:15 UTC, TAK848 commented on tweets/urls.py
> +        "<str:username>/<int:pk>/", views.TweetDetailView.as_view(), name="tweet_detail"
Okです！
一応
<username>/tweets/<pk>/
にすれば仕様的には近づきますね！

2022-09-20 11:16 UTC, TAK848 approved these changes
LGTM!!

2022-09-20 15:34 UTC, merged